wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692774096.997086
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      - 103
      3:
      - 7
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 1
      - 3
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
